version: '{branch}-{build}'
install:
- appveyor DownloadFile https://github.com/w3c/epubcheck/releases/download/v4.1.1/epubcheck-4.1.1.zip
- ps: 7z x epubcheck-4.1.1.zip
- npm install @daisy/ace -g

build_script:
- cmd: epubsave.bat

artifacts:
- path: '*.nvda-addon'
  name: addon
  type: WebDeployPackage
  
before_deploy:
- ps: $env:REPO_NAME =  $env:APPVEYOR_REPO_NAME.Substring($env:APPVEYOR_REPO_NAME.IndexOf('/') + 1)

deploy:
- provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: Release $(APPVEYOR_REPO_TAG_NAME)
  description: This is the release $(APPVEYOR_REPO_TAG_NAME) of the $(REPO_NAME) addon for the NVDA screen reader built and uploaded to GitHub using Appveyor.

  auth_token:
    secure: 3yxF2EQ/wfLKNEobcRfdNL6srjXjoMdRa/LSQ7z2PJNqOL3IEyiFtlnxxHeIQskH
  artifact: addon
  on:
    appveyor_repo_tag: true