---
title: nvdaes.github.io/epub-accessibility-tests
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: epub-accessibility-tests en español
description: Documentación en español sobre el [proyecto epub-accessibility-tests del consorcio DAISY](https://github.com/daisy/epub-accessibility-tests)
avatar: https://raw.githubusercontent.com/barryclark/jekyll-now/master/images/jekyll-logo.png
footer-links:
  dribbble: 
  email: 
  facebook: 
  flickr: 
  github: nvdaes
  instagram: 
  linkedin: 
  pinterest: 
  rss: 
  twitter: 
  stackoverflow: 
  youtube: 
  googleplus: 
disqus: 
google_analytics: 
url: 
baseurl: 'https://nvdaes.github.io/epub-accessibility-tests'
permalink: "/:title/"
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: highlight
sass:
  style: :expanded
gems:
- jekyll-sitemap
- jekyll-feed
exclude:
- Gemfile.lock
- LICENSE
- README.md
- CNAME
authors:
  Noelia:
    name: Noelia
    display_name: Noelia
    web: https://nvdaes.github.io/noelia

